// Dashboard webview logic
// This file is used as reference for the dashboard webview panel.
// The actual dashboard logic is embedded in src/dashboard.ts as inline HTML
// to work within VS Code's webview security constraints.

interface DashboardState {
    totalItems: number;
    affectedFiles: number;
    scannedFiles: number;
    cleanScore: number;
    scanDuration: number;
    byType: Record<string, number>;
    byLanguage: Record<string, number>;
    topFiles: Array<{ path: string; count: number }>;
    history: Array<{ timestamp: number; deadCount: number; cleanScore: number }>;
}

declare function acquireVsCodeApi(): {
    postMessage(message: unknown): void;
    getState(): unknown;
    setState(state: unknown): void;
};

const vscode = acquireVsCodeApi();

function runScan(): void {
    vscode.postMessage({ command: 'scan' });
}

function exportReport(): void {
    vscode.postMessage({ command: 'exportReport' });
}

function copyBadge(): void {
    vscode.postMessage({ command: 'copyBadge' });
}

window.addEventListener('message', (event) => {
    const message = event.data;
    switch (message.command) {
        case 'update':
            updateDashboard(message.data as DashboardState);
            break;
    }
});

function updateDashboard(state: DashboardState): void {
    const content = document.getElementById('content');
    if (!content) { return; }
    // Dashboard update logic is handled inline in the webview HTML
    // generated by src/dashboard.ts
}
